ForgeRock/ping-android-sdk

davinci/src/androidTest/kotlin/com/pingidentity/davinci/Davinci-E2E-Flows.json
davinci/src/androidTest/kotlin/com/pingidentity/davinci/DavinciAndroidTest.kt
samples/app/src/main/java/com/pingidentity/samples/app/davinci/DaVinciViewModel.kt

- [SDKS-3360](https://pingidentity.atlassian.net/browse/SDKS-3360) Test Cases for DaVinci
The OOTB "PingOne SignOn With Sessions" [flow pack](https://support.pingidentity.com/s/marketplace-integration/a7iDo00000110R2IAI/pingone-sign-on-with-sessions) have been updated recently. 
With this PR the e2e test cases have been updated to cover the changes + added test coverage for the "account locked" flow. Also, the test cases have been aligned with the iOS test cases...

SDKS-3360 - Update E2E Test Cases for DaVinci

---

README.md
build-logic/convention/src/main/kotlin/com/pingidentity/convention/MavenCentralPublishConventionPlugin.kt

[SDKS-3599](https://pingidentity.atlassian.net/browse/SDKS-3599)
SDKS-3599 Rename unified-sdk-android to ping-android-sdk

SDKS-3599 Rename unified-sdk-android to ping-android-sdk

---

davinci/src/main/kotlin/com/pingidentity/davinci/User.kt
davinci/src/main/kotlin/com/pingidentity/davinci/module/Transform.kt
davinci/src/test/kotlin/com/pingidentity/davinci/DaVinciErrorTest.kt
foundation/utils/src/main/kotlin/com/pingidentity/exception/Catch.kt
journey/src/main/kotlin/com/pingidentity/journey/User.kt
journey/src/main/kotlin/com/pingidentity/journey/module/Session.kt

[SDKS-3607](https://pingidentity.atlassian.net/browse/SDKS-3607)
SDKS-3607 Handle 300..399 redirect response with empty body

SDKS-3607 Handle 300..399 redirect response with empty body

---

foundation/storage/src/main/kotlin/com/pingidentity/storage/encrypt/SecretKeyEncryptor.kt
gradle/libs.versions.toml
samples/app/build.gradle.kts
samples/journeyapp/build.gradle.kts

[https://pingidentity.atlassian.net/browse/SDKS-3597](SDKS-3597)
SDKS-3597 Update Ping SDK Minimum Supported Version to API Level 28

SDKS-3597 Update Ping SDK Minimum Supported Version to API Level 28

---

davinci/src/main/kotlin/com/pingidentity/davinci/DaVinci.kt
davinci/src/test/kotlin/com/pingidentity/davinci/DaVinciTest.kt
external-idp/src/main/kotlin/com/pingidentity/idp/davinci/FacebookHandler.kt
external-idp/src/main/kotlin/com/pingidentity/idp/davinci/GoogleHandler.kt
samples/app/build.gradle.kts

Please link jira ticket here
[SDKS-3602](https://pingidentity.atlassian.net/browse/SDKS-3602)
Update the x-requested-with header in SDK requests from forgerock-sdk to ping-sdk

SDKS-3602 Replace x-requested-with Header in SDK

---

samples/app/src/main/java/com/pingidentity/samples/app/AppDrawer.kt
samples/app/src/main/java/com/pingidentity/samples/app/AppNavHost.kt
samples/app/src/main/java/com/pingidentity/samples/app/LogoutViewModel.kt
samples/app/src/main/java/com/pingidentity/samples/app/Setting.kt
samples/app/src/main/java/com/pingidentity/samples/app/User.kt
samples/app/src/main/java/com/pingidentity/samples/app/centralize/CentralizeLoginViewModel.kt
samples/app/src/main/java/com/pingidentity/samples/app/davinci/DaVinciViewModel.kt
samples/app/src/main/java/com/pingidentity/samples/app/env/Env.kt
samples/app/src/main/java/com/pingidentity/samples/app/env/EnvViewModel.kt

[SDKS-3642](https://pingidentity.atlassian.net/browse/SDKS-3642)
SDKS-3642 Enable Dynamic Environment Switching in Test App

SDKS-3642 Enable Dynamic Environment Switching in Test App

---

davinci/src/main/kotlin/com/pingidentity/davinci/CollectorRegistry.kt
davinci/src/main/kotlin/com/pingidentity/davinci/collector/Collectors.kt
davinci/src/main/kotlin/com/pingidentity/davinci/collector/MultiSelectCollector.kt
davinci/src/test/kotlin/com/pingidentity/davinci/CollectorRegistryTest.kt
davinci/src/test/kotlin/com/pingidentity/davinci/DaVinciTest.Response.kt
davinci/src/test/kotlin/com/pingidentity/davinci/MultiSelectCollectorTest.kt
davinci/src/test/resources/ResponseWithBasicType.json
foundation/davinci-plugin/src/main/kotlin/com/pingidentity/davinci/plugin/CollectorFactory.kt

[SDKS-3731](https://pingidentity.atlassian.net/browse/SDKS-3731)
SDKS-3731 Align New Response Contract from PingOne Form

SDKS-3731 Align New Response Contract from PingOne Form

---

davinci/src/androidTest/kotlin/com/pingidentity/davinci/Form-Field-Tests-Flow.json
davinci/src/androidTest/kotlin/com/pingidentity/davinci/FormFieldValidationTest.kt
davinci/src/androidTest/kotlin/com/pingidentity/davinci/FormFieldsTest.kt

[SDKS-3806](https://pingidentity.atlassian.net/browse/SDKS-3806) QA of the new response contract from PingOne Forms
- Added test coverage for the default values of the PingOne Forms fields
- Added test coverage for the Error node

SDKS-3806 Add test coverage for the default values of P1 form fields

---

davinci/src/androidTest/kotlin/com/pingidentity/davinci/FormFieldValidationTest.kt
davinci/src/main/kotlin/com/pingidentity/davinci/collector/PasswordCollector.kt
davinci/src/test/kotlin/com/pingidentity/davinci/PasswordCollectorTest.kt

[SDKS-3864](https://pingidentity.atlassian.net/browse/SDKS-3864)
SDKS-3864 Temporary remove the password policy implementation.

SDKS-3864 Temporary remove the password policy implementation.

---

davinci/README.md
davinci/src/main/kotlin/com/pingidentity/davinci/DaVinci.kt
davinci/src/main/kotlin/com/pingidentity/davinci/module/Connector.kt
davinci/src/main/kotlin/com/pingidentity/davinci/module/ErrorNode.kt
davinci/src/main/kotlin/com/pingidentity/davinci/module/Transform.kt
davinci/src/test/kotlin/com/pingidentity/davinci/DaVinciErrorTest.kt
davinci/src/test/kotlin/com/pingidentity/davinci/DaVinciTest.kt
foundation/orchestrate/src/main/kotlin/com/pingidentity/orchestrate/Node.kt
foundation/orchestrate/src/test/kotlin/com/pingidentity/divinci/WorkflowTest.kt
journey/src/main/kotlin/com/pingidentity/journey/module/Transform.kt
samples/app/src/main/java/com/pingidentity/samples/app/davinci/DaVinci.kt
samples/app/src/main/java/com/pingidentity/samples/app/davinci/DaVinciState.kt
samples/app/src/main/java/com/pingidentity/samples/app/davinci/DaVinciViewModel.kt

[SDKS-3890](https://pingidentity.atlassian.net/browse/SDKS-3890)
Access Previous Continue Node from ErrorNode

SDKS-3890 Access Previous Continue Node from ErrorNode

---

davinci/src/androidTest/kotlin/com/pingidentity/davinci/FormFieldsTest.kt
davinci/src/main/kotlin/com/pingidentity/davinci/collector/LabelCollector.kt
davinci/src/test/kotlin/com/pingidentity/davinci/LabelCollectorTest.kt

[SDKS-3957](https://pingidentity.atlassian.net/browse/SDKS-3957)
SDKS-3957 Add "key" attribute for LabelCollector

SDKS-3957 Add "key" attribute for LabelCollector

---

davinci/src/main/kotlin/com/pingidentity/davinci/collector/PhoneNumberCollector.kt
davinci/src/test/kotlin/com/pingidentity/davinci/PhoneNumberCollectorTest.kt
samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/PhoneNumber.kt

[SDKS-3871](https://pingidentity.atlassian.net/browse/SDKS-3871)
SDKS-3871 Handle initial value of PhoneNumber Type.

SDKS-3871 Handle initial value of PhoneNumber Type.

---

davinci/src/main/kotlin/com/pingidentity/davinci/collector/Device.kt
davinci/src/main/kotlin/com/pingidentity/davinci/collector/DeviceAuthenticationCollector.kt
davinci/src/test/kotlin/com/pingidentity/davinci/DeviceAuthenticationCollectorTest.kt
davinci/src/test/kotlin/com/pingidentity/davinci/DeviceRegistrationCollectorTest.kt
samples/app/src/main/java/com/pingidentity/samples/app/davinci/collector/DeviceAuthentication.kt

[SDKS-4079](https://pingidentity.atlassian.net/browse/SDKS-4079)
SDKS-4079 DeviceRegistrationCollector and DeviceAuthenticationCollector contract update.

SDKS-4079 DeviceRegistrationCollector and DeviceAuthenticationCollector contract update.

---

.github/workflows/mend-cli-scan.yaml
CHANGELOG.md
external-idp/build.gradle.kts
foundation/android/build.gradle.kts
foundation/browser/build.gradle.kts
foundation/davinci-plugin/build.gradle.kts
foundation/journey-plugin/build.gradle.kts
foundation/logger/build.gradle.kts
foundation/oidc/build.gradle.kts
foundation/orchestrate/build.gradle.kts
foundation/storage/build.gradle.kts
foundation/utils/build.gradle.kts

[SDKS-4076](https://pingidentity.atlassian.net/browse/SDKS-4076) Release activities for Ping SDK 1.2.0 
- Updated CHANGELOG.md
- Added description in build.gradle files for all SDK modules

SDKS-4076 Release activities for Ping SDK 1.2.0

---

journey/src/main/kotlin/com/pingidentity/journey/Constants.kt
journey/src/main/kotlin/com/pingidentity/journey/Journey.kt
journey/src/test/kotlin/com/pingidentity/journey/JourneyTest.kt

[SDKS-4170](https://pingidentity.atlassian.net/browse/SDKS-4170)
SDKS-4170 Add x-requested-with and x-requested-platform header

SDKS-4170 Add x-requested-with and x-requested-platform header

---

davinci/build.gradle.kts
foundation/storage/README.md
foundation/storage/src/androidTest/kotlin/com/pingidentity/storage/EncryptedDataStoreStorageFactoryTest.kt
foundation/storage/src/androidTest/kotlin/com/pingidentity/storage/EncryptedDataStoreStorageTest.kt
foundation/storage/src/main/kotlin/com/pingidentity/storage/DataStorePreferencesStorage.kt
foundation/storage/src/main/kotlin/com/pingidentity/storage/DataStoreStorage.kt
foundation/storage/src/main/kotlin/com/pingidentity/storage/EncryptedDataStoreStorage.kt
foundation/storage/src/main/kotlin/com/pingidentity/storage/EncryptedDataStoreStorageFactory.kt
foundation/storage/src/main/kotlin/com/pingidentity/storage/StorageDelegate.kt
foundation/storage/src/test/kotlin/com/pingidentity/storage/DataStorageTest.kt
foundation/storage/src/test/kotlin/com/pingidentity/storage/StorageDelegateTest.kt
journey/README.md
samples/app/build.gradle.kts

[SDKS-4112](https://pingidentity.atlassian.net/browse/SDKS-4112)
Enhance Storage Module with Cache Strategy Support

SDKS-4112 Enhance Storage Module with Cache Strategy Support

---

journey/src/main/kotlin/com/pingidentity/journey/callback/KbaCreateCallback.kt
journey/src/test/kotlin/com/pingidentity/journey/callback/KbaCreateCallbackTest.kt
samples/journeyapp/src/main/java/com/pingidentity/samples/journeyapp/journey/callback/KbaCreateCallback.kt

[SDKS-4276](https://pingidentity.atlassian.net/browse/SDKS-4276)
SDKS-4276 Handle allowUserDefinedQuestions in KbaCreateCallback

SDKS-4276 Handle allowUserDefinedQuestions in KbaCreateCallback

---

build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

[SDKS-4215](https://pingidentity.atlassian.net/browse/SDKS-4215)
SDKS-4215 Fix Maven publishing

SDKS-4215 Fix Maven publishing

---

external-idp/src/main/kotlin/com/pingidentity/idp/journey/AppleHandler.kt
external-idp/src/main/kotlin/com/pingidentity/idp/journey/IdpCallback.kt
external-idp/src/test/kotlin/com/pingidentity/idp/davinci/CollectorRegistryTest.kt
external-idp/src/test/kotlin/com/pingidentity/idp/journey/AppleHandlerTest.kt
external-idp/src/test/kotlin/com/pingidentity/idp/journey/CallbackInitializerTest.kt
external-idp/src/test/kotlin/com/pingidentity/idp/journey/IdpCallbackTest.kt
external-idp/src/test/kotlin/com/pingidentity/idp/journey/SelectIdpCallbackTest.kt

[SDKS-4129](https://pingidentity.atlassian.net/browse/SDKS-4129)
SDKS-4129 Implement Native Social Login for FB, Google and Apple for PingAM/AIC

SDKS-4129 Implement Native Social Login for FB, Google and Apple for PingAM/AIC

---

external-idp/src/main/kotlin/com/pingidentity/idp/IdpHandler.kt
external-idp/src/main/kotlin/com/pingidentity/idp/journey/IdpCallback.kt
external-idp/src/main/kotlin/com/pingidentity/idp/journey/SelectIdpCallback.kt

[SDKS-3898](https://pingidentity.atlassian.net/browse/SDKS-3898)
SDKS-3898 Minor enhancement to align with iOS Native Social Login Implementation

SDKS-3898 Minor enhancement to align with iOS Native Social Login Implementation

---

foundation/oidc/src/main/kotlin/com/pingidentity/oidc/OidcClientConfig.kt
foundation/orchestrate/src/main/kotlin/com/pingidentity/orchestrate/module/Cookie.kt
journey/src/main/kotlin/com/pingidentity/journey/module/Session.kt
journey/src/main/kotlin/com/pingidentity/journey/module/SessionConfig.kt

[SDKS-4358](https://pingidentity.atlassian.net/browse/SDKS-4358)
Refactor logger initialization in session and cookie configurations
- Update SessionConfig, CookieConfig, and OidcClientConfig to initialize their respective loggers.
- In Session module, ensure the logger in SessionConfig is set before initialization.
- In Cookie module, ensure the logger in CookieConfig is set before initialization.

SDKS-4358 Refactor logger initialization in session and cookie configurations

---

davinci/build.gradle.kts
davinci/src/androidTest/kotlin/com/pingidentity/davinci/DavinciProtectTest.kt
davinci/src/androidTest/kotlin/com/pingidentity/davinci/PingOne-Protect-Flows.json
journey/build.gradle.kts
journey/src/androidTest/kotlin/com/pingidentity/journey/callback/MetadataCallbackE2ETest.kt
journey/src/androidTest/kotlin/com/pingidentity/journey/callback/PingOneProtectEvaluationCallbackE2ETest.kt
journey/src/androidTest/kotlin/com/pingidentity/journey/callback/PingOneProtectInitializeCallbackE2ETest.kt
journey/src/androidTest/kotlin/com/pingidentity/journey/callback/test-journeys/TEST_PING_ONE_PROTECT_EVALUATE.journey.json
journey/src/androidTest/kotlin/com/pingidentity/journey/callback/test-journeys/TEST_PING_ONE_PROTECT_INITIALIZE.journey.json

[SDKS-4070](https://pingidentity.atlassian.net/browse/SDKS-4070) QA Testing for Ping Protect SDK Integration
- Added e2e test cases for PingOne Protect support in the DaVinci module
- Added e2e test cases for PingOne Protect support in the Journey module (AIC)

SDKS-4070 E2E Tests for PingOne Protect Integration in DaVinci Module
